### ISSUE TITLE
add Fake / Mock for testing

### ISSUE THREAD

**Issue by ashleyschuett** [containership/csctl#95] opened 2019-03-20 14:47 UTC
### Description

There should be some kind of package in this repo to make it easy to test in other repositories when using this tool. We will need to take the time to investigate what makes the most sense. 

See: https://github.com/containership/infrastructure-controller/pull/18#discussion_r267373095

**Comment by mattkelly** [comment] 2019-03-20 14:53
Closing as a dupe of https://github.com/containership/csctl/issues/57 :)

**Closed by mattkelly** 2019-03-20 14:53 UTC
